# Default Configurations
default_config:

# HTTP Settings
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.0.0/24
  cors_allowed_origins:
    - http://localhost:4200

# Frontend Themes
frontend:
  themes: !include_dir_merge_named themes

# Text to Speech
tts:
  - platform: google_translate
    language: "en"

# Includes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
fan: !include fans.yaml

# Database Recorder
recorder:
  db_url: !secret recorder_db_url

# Wake on LAN
wake_on_lan:

homekit: !include homekit.yaml

# MQTT Configuration
mqtt:
  sensor:
    - name: "shelly1l_input_0"
      state_topic: "shellies/shelly1l-98CDAC2FC4B9/input/0"
    - name: "shelly1l_input_1"
      state_topic: "shellies/shelly1l-98CDAC2FC4B9/input/1"
    - name: "shelly1l_armario_input_0"
      state_topic: "shellies/shelly1l-98CDAC2F71D0/input/0"
    - name: "shelly1l_armario_input_1"
      state_topic: "shellies/shelly1l-98CDAC2F71D0/input/1"

# Light Template
light:
  - platform: template
    lights:
      shelly_habitacion_mqtt:
        unique_id: shelly_habitacion_mqtt_01
        friendly_name: "Luz Ventilador Habitacion"
        turn_on:
          action: input_boolean.toggle
          entity_id: input_boolean.luz_habitacion
        turn_off:
          action: input_boolean.toggle
          entity_id: input_boolean.luz_habitacion
        value_template: "{{ is_state('input_boolean.luz_habitacion', 'on') }}"

# Input Text Configuration
input_text:
  agent_personality:
    name: Agent Personality
    min: 0
    max: 255

template:
  - sensor:
      - name: "Current Temperature"
        unique_id: "current_temperature_sensor"
        unit_of_measurement: "°C"
        state: "{{ states.weather.forecast_matematico.attributes.temperature }}"
        device_class: temperature
      - name: "Current Humidity"
        unique_id: "current_humidity_sensor"
        unit_of_measurement: "%"
        state: "{{ states.weather.forecast_matematico.attributes.humidity }}"
        device_class: humidity
      - name: "Weather Condition"
        unique_id: "weather_condition_sensor"
        state: "{{ states.weather.forecast_matematico.state }}"

sensor:
  - platform: snmp
    name: "TerraMaster Disk Usage"
    host: 192.168.0.237
    community: "public"
    version: "2c"
    baseoid: 1.3.6.1.2.1.25.2.3.1.6.1
    unit_of_measurement: "%"
    value_template: >
      {% set used = value | int %}
      {% set total = states('sensor.terramaster_disk_total') | int %}
      {{ ((used / total) * 100) | round(2) }}
  - platform: snmp
    name: "TerraMaster Disk Total"
    host: 192.168.0.237
    community: "public"
    version: "2c"
    baseoid: 1.3.6.1.2.1.25.2.3.1.5.1
    unit_of_measurement: "GB"
    value_template: "{{ (value | int * 4096 / 1073741824) | round(2) }}"
